blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/opencarbox/opencarbox/security/policy
    about: Please review our security policy before reporting private vulnerabilities.
